#!/bin/sh /etc/rc.common
#To use circle function,please identify the value of "mount_dev"
START=96
boot() {
	factory_mode_flag=`/bin/config get factory_mode`
	if [ "x$factory_mode_flag" = "x1" ]; then
		exit 0
	fi

	#Check if project support circle feature
	if [ "x`/bin/config get dgc_func_have_circle`" != "x1" ]; then
		exit 0
	fi

	#Check if circle is disabled
	if [ "`/bin/config get nocircle`" = "1" ]; then
		exit 0
	fi

	#format partition
	mount_dev=`part_dev circle`
	if [ -b $mount_dev ];then
		[ "x$mount_dev" != "x" ] && filetype=`blkid $mount_dev |grep -o 'TYPE=.*' |awk -F \" '{print $2}' | cut -c 1-3`
		if [ "x$filetype" != "xext" ];then
			mkfs.ext4 $mount_dev
		fi
	fi
	
	if [ "x`cat /tmp/orbi_type`" != "xBase" ]; then
		exit 0
	fi

	local router_region=`artmtd -r region |grep REGION|awk -F ': ' '{print $2}'`
	if [ "x$router_region" = "xPR" ]; then
		exit 0
	fi

	#insmod circle_pcc.ko
	kernel_version=`uname -a | awk -F " " '{print $3}'`
	#insmod /lib/modules/$kernel_version/circle_pcc.ko

	#circled start
	local circle_module_name=`cat /module_name | tr '[A-Z]' '[a-z]'`
	local circle_path=`echo "https://http.fw.updates1.netgear.com/sw-apps/parental-control/circle/$circle_module_name/mr22/"`
	local server_path=`/bin/config get "server_path"`
	if [ "x$server_path" != "x" ]; then
		circle_path=`echo "https://http.fw.updates1.netgear.com/$server_path/sw-apps/parental-control/circle/$circle_module_name/mr22/"`
	fi
	echo "$circle_path" >> /tmp/circle_down_path
	/usr/sbin/net-wall restart	
	local enable_circle_plc=`/bin/config get "enable_circle_plc"`
	partition_type=`cat /flash_type`
	if [ "x$partition_type" != "xEMMC" ]; then
		ubidev=$(ubinfo -a | grep -B5 vol_circle | sed -nr 's/Volume ID:.*\(on (ubi.*)\)/\1/p')
		if [ "$ubidev" = "" -a "$(ubinfo -a | grep vol_ntgrdata)" != "" ]; then
			#For project RBR10
			have_vol_ntgrdata=1
			argv_part=
		else
			argv_part="-U $ubidev"
		fi
	else
		partition_num=`echo "$mount_dev" | awk -F '/' '{printf $3}'`
		argv_part="-P $partition_num"
	fi

	if [ "x`mount |grep '/tmp/mnt/circle'`" = "x" -a "$have_vol_ntgrdata" = "" ]; then
		[ ! -d '/tmp/mnt/circle' ] && mkdir '/tmp/mnt/circle'
		if [ "x$partition_type" != "xEMMC" ]; then
			mount -t ubifs $ubidev:vol_circle '/tmp/mnt/circle'
		else
			mount $mount_dev '/tmp/mnt/circle'
		fi
	elif [ "$have_vol_ntgrdata" = "1" ]; then
		[ ! -d "/tmp/ntgrdata/circle" ] && mkdir -p "/tmp/ntgrdata/circle"
		ln -s "/tmp/ntgrdata/circle" '/tmp/mnt/circle'
	fi

	agent_version_type=`cat /mnt/circle/shares/VERSION |awk -F '.' '{print NF}'`
	#When the firmware is switching from MR2.1 to MR2.2
	if [ $agent_version_type = "4" ]; then
		rm /mnt/circle/shares/VERSION
	fi
	
	if [ "x`/bin/config get i_opmode`" != "xapmode" ]; then
		if [ "$enable_circle_plc" = "1" ]; then
			/usr/bin/circled nostart $argv_part &
		else
			/usr/bin/circled nostart $argv_part &
		fi
		/etc/init.d/check_connect &
	
		#For GUI promtp window
		/bin/config set "reboot_flag_for_circle=1"
	else
		/bin/config set "reboot_flag_for_circle=0"
	fi
	/etc/init.d/dnsmasq restart

}	
