#!/bin/sh

PPP_IFNAME="ppp0"
WAN_IFNAME="brwan"
LAN_IFNAME="br0"
INTERVAL=300

gw_detect()
{
	if [ "$(/bin/config get ap_mode)" = "1" ];then
		ifname=$LAN_IFNAME
		ip=`route -n |grep $ifname | grep 0.0.0.0 |awk '{print $2}' |grep -v 0.0.0.0`
	elif [ "$(/bin/config get wan_proto)" = "pppoe" -o "$(/bin/config get wan_proto)" = "pptp" -o "$(/bin/config get wan_proto)" = "l2tp" ]; then
		ifname=$PPP_IFNAME
		ip=`route -n |grep $ifname | grep 0.0.0.0 |awk '{print $1}' |grep -v 0.0.0.0`
	else
		ifname=$WAN_IFNAME
		ip=`route -n |grep $ifname | grep 0.0.0.0 |awk '{print $2}' |grep -v 0.0.0.0`
	fi

	if [ "x$ip" = "x" ];then
		old_gwdiconnection=`/bin/config get gwDisconnDuration`
		let old_gwdiconnection=old_gwdiconnection+5
		/bin/config set gwDisconnDuration=$old_gwdiconnection
		return
	fi
	ping -c 2 $ip > /tmp/ping_gw_result 2> /dev/null
	sleep 5
	result=`cat /tmp/ping_gw_result`

	if [ "x$result" = "x" ];then
		old_gwdiconnection=`/bin/config get gwDisconnDuration`
		let old_gwdiconnection=old_gwdiconnection+5
		/bin/config set gwDisconnDuration=$old_gwdiconnection
	else
		if [ "x$(echo $result |grep "100% packet loss")" != "x" ]; then
			old_gwdiconnection=`/bin/config get gwDisconnDuration`
			let old_gwdiconnection=old_gwdiconnection+5
			/bin/config set gwDisconnDuration=$old_gwdiconnection
		fi
	fi
}

while true
do
	gw_detect
	sleep $INTERVAL
done
