#!/bin/sh /etc/rc.common

START=99
STOP=99
SERVICE=/sbin/wifison-monitor.sh
USE_PROCD=1

start_service()
{
    procd_open_instance
    procd_set_param command $SERVICE
    procd_set_param respawn
    procd_close_instance
}



