###################################################
# Makefile for the NSS GMAC driver
###################################################

obj ?= .

obj-m += ipt_iparray_match.o

# Un-comment this line to build with emulation platform support
#ccflags-y += -DRUMI_EMULATION_SUPPORT
