#!/bin/sh /etc/rc.common

START=98
STOP=30

PATH=/bin:/sbin:/usr/bin:/usr/sbin
DROPBEAR="/usr/sbin/dropbear"
PIDFILE="/var/run/dropbear.pid"
PORT=22

start() {
	# Set TimeZone for console
	tz=$($CONFIG get time_zone)
	echo "$tz" > /tmp/TZ

	# Start SSH server
	$DROPBEAR -p $PORT -a -P $PIDFILE
	/usr/sbin/net-wall rule
	/usr/sbin/net-wall start
	/usr/sbin/net-wall -6 rule
	/usr/sbin/net-wall -6 start
}

stop() {
	# Stop SSH server
	kill `cat $PIDFILE`
}
